networks:
  billing_network:
    driver: bridge

services:
  db_mongo:
    image: mongo:8
    container_name: db_mongo
    ports:
      - 27017:27017
    volumes:
      - ./tmp/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - billing_network
    extra_hosts:
      - host.docker.internal:host-gateway
  billing_api:
    build:
      context: .
      dockerfile: ./apps/billingApi/Dockerfile
    entrypoint: ["sh", "-c", "npm install && nx serve billingApi"]
    container_name: billing_api
    ports:
      - 3000:3000
    environment:
      MONGO_CONNECTION: "mongodb://root:example@host.docker.internal:27017/billing?authSource=admin"
      NX_DAEMON: true
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
      OTEL_METRICS_ENABLED: "false"
      OTEL_SERVICE_NAME: "billing-api"
      OTEL_SERVICE_VERSION: "0.0.1"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_METRIC_EXPORT_INTERVAL: "10000"
    volumes:
      - .:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db_mongo
      # - otel-collector
    networks:
      - billing_network
  # otel-collector:
  #   image: otel/opentelemetry-collector:latest
  #   container_name: otel-collector
  #   ports:
  #     - 4318:4318
  #     - 8889:8889
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   environment:
  #     GOGC: 80
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   networks:
  #     - billing_network
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   user: "0:0"
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  #     - ./tmp/prometheus:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #   networks:
  #     - billing_network
  #   depends_on:
  #     - otel-collector
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   user: "0:0"
  #   ports:
  #     - 3001:3000
  #   environment:
  #     GF_SECURITY_ADMIN_PASSWORD: admin
  #     GF_USERS_ALLOW_SIGN_UP: "false"
  #     GF_PATHS_DATA: /var/lib/grafana
  #   volumes:
  #     - ./tmp/grafana:/var/lib/grafana
  #   networks:
  #     - billing_network
  #   depends_on:
  #     - prometheus
